// This file was generated by PermissionsDispatcher. Do not modify!
package com.hfc.permissions_annotations.helper;

import android.app.Activity;
import android.content.Context;
import android.util.Log;
import java.lang.ref.WeakReference;

final class BerthModifyActivityPermissionsDispatcher {
 /* private static final int REQUEST_GETPERMISSION = 22;

  private static final String[] PERMISSION_GETPERMISSION = new String[] {"android.permission.CAMERA"};

  private BerthModifyActivityPermissionsDispatcher() {
  }

  static void getPermissionWithCheck(Activity activity) {
    PermissionHelper.getPermissionWithCheck(activity,()->{},(handler)->{},()->{}, REQUEST_GETPERMISSION,PERMISSION_GETPERMISSION);
  }

  static void onRequestPermissionsResult(Activity target, int requestCode,
      int[] grantResults) {
    switch (requestCode) {
      case REQUEST_GETPERMISSION:
      PermissionHelper.onRequestPermissionsResult(target,()->{},()->{},()->{},grantResults,PERMISSION_GETPERMISSION);
      break;
      default:
      break;
    }
  }
*/
}
